### ISSUE TITLE
There is no price threshold being set

### ISSUE THREAD

**Issue by RXWatcher1** [alexanderdean111/hatchimal_hunter#1]
Can you please update it with the price threshold?
The default value isnt being set.

Otherwise it's working!

Thanks!

**Comment by alexanderdean111** [comment]
Price threshold should now be configurable in the config file (check the provided one) and the default is set.  Release version was setting it properly for me, were you seeing the issue there as well or just with the command line version?

**Comment by RXWatcher1** [comment]
running it on linux command line.
couple of things to note:
you'll notice a double forward slack after walmart.com.
I had to do a pip install requests as requests was missing.

I hacked the script to limit the price:
if "hatchimal" in item_name.lower() \
            and not out_of_stock and item_price < **float(100):**


The emails would have prices all over place..$200+ and up. An example:

=== Begin Auto Alert ===
 Hatchimals - Hatching Egg - Interactive Creature - Draggle - Blue/Purple Egg by Spin Master
$230.34
https://www.walmart.com//ip/Hatchimals-Draggles-By-Spin-Master/50676611
====================
 Hatchimals - Hatching Egg - Interactive Creature - Penguala - Pink Egg by Spin Master
$207.97
https://www.walmart.com//ip/Hatchimals-Pengualas-By-Spin-Master/50676599
====================
 Hatchimals - Hatching Egg - Interactive Creature - Penguala - Pink/Teal Egg by Spin Master
$214.95
https://www.walmart.com//ip/Hatchimals-Pengualas-By-Spin-Master/50676589
====================
 Hatchimals - Hatching Egg - Interactive Creature - Draggle - Blue/Green Egg by Spin Master
$208.89
https://www.walmart.com//ip/Hatchimals-Draggles-By-Spin-Master/50676591

**Comment by alexanderdean111** [comment]
The issue I saw was line 73 that was passing "800" as the threshold, which was what I put in just to force an alert while I was testing it.  I have since changed that to line to:
alerts = check_walmart(config['price_threshold'])
so that it pulls the threshold from the config file rather than something hardcoded.

Try running the latest version (39ae651)
